# Generated by Django 4.2.2 on 2023-07-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_options_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
    ]
